{
	"version": 1738586217,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/play-sheet0.png",
		"images/bg-sheet0.png",
		"images/seesaw-sheet0.png",
		"images/minion-sheet0.png",
		"images/minion-sheet1.png",
		"images/anchor-sheet0.png",
		"images/gru-sheet0.png",
		"images/moon-sheet0.png",
		"images/sprite-sheet0.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/jump 3.m4a",
		"media/jump 3.ogg",
		"media/catching the moon.m4a",
		"media/catching the moon.ogg",
		"media/bg (1).m4a",
		"media/bg (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}